[book]
authors = ["The Zed Team"]
language = "en"
multilingual = false
src = "src"
title = "Zed"

[output.html]
no-section-label = true
preferred-dark-theme = "dark"
additional-css = [
    "theme/page-toc.css",
    "theme/plugins.css",
    "theme/highlight.css",
]
additional-js = ["theme/page-toc.js", "theme/plugins.js"]

[output.html.print]
enable = false
